### ISSUE TITLE
Incorrect 7bit-encode

### ISSUE THREAD

**Issue by borokovic** [jackkum/node-pdu#31]
Encode7bit produces incorrect for some strings.
For example:
`*171*1*1*5*085767240000*123456#` generates
AAD82DA68AA962AA9A0A86ABDD6C37190D0683C15431D98C56B38D00 
which should be 
AAD82DA68AA962AA9A0A86ABDD6C37190D0683C15431D98C56B38D1A

`http://smstools3.kekekasvi.com/topic.php?id=288`

**Comment by KillerJulian** [comment]
Thanks for the issue.

Please provide more information (e.g. a code example) to reproduce the error.

**Comment by borokovic** [comment]
const Enkoding = require("node-pdu/PDU/Helper");
const cmd = "*171*1*1*5*085767240000*123456#";
const perintah = Enkoding.encode7Bit(cmd);
console.log(perintah);

**Comment by KillerJulian** [comment]
I can achieve the desired result by appending a `\r` to your input. Is this an error the `Helper.encode7Bit()` function or on your part?

```js
const pdu = require('./dist/index');

const cmd = '*171*1*1*5*085767240000*123456#\r';
const perintah = pdu.utils.Helper.encode7Bit(cmd);

console.log(perintah);
```
