### ISSUE TITLE
Error on encode multi-part message with report enabled.

### ISSUE THREAD

**Issue by rubensfernandes** [jackkum/node-pdu#8]
I'm trying to encode this message: 'sms_manu_pfofensor_3005, seu acordo esta em atraso, evite que o desconto seja cancelado. Caso ja tenha efetuado o pagamento favor enviar o comprovante para boletospf@liderancacobrancas.com.br para baixa em sistema.'

Part 1: F3F6FCDB0EBBEB5FB8F96D2EBBE76FF9770683D558A079B90E0A8FDF72F21B549ED3C3A0721B14A6CBC3F3370B54B6A7E96550BC5E06BD41E4F27CFC76D3DFA079591D068DC3EE71991D26BF5DA06178FE06A9C3207AD98D0E83CAE632BD1E26BF416F103C7C0EB7CB6EFA1B640EDBDF7250D96D4F87E5A03768FC6EC3E56F7BD84D2F83E0

Part 2: 
617918247EB3CBF4F71C6E06B2D3E4B23CEC1E87C76FB13CEC1E87E7AEF1BBED12CB41F0B03C0C1287D3F830A8DC06CDD3737AB91D7601

but the Pdu is not reconized here: https://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-submit-pdu-decoder/

Can you help me?

**Comment by jackkum** [comment]
This is because it not a valid a pdu string. 
Structure of pdu you can see here
![pdu](https://cloud.githubusercontent.com/assets/2418167/26659525/ddbdb5a4-46a3-11e7-9c1e-3528cdda01f8.jpg)

In your case this is only a user data (UD) encoded by 7 bit alphabet. 

I added the method getHelper() yo can use it like that:
```javascript
var Helper = PDU.getHelper();
var parts  = [
  'F3F6FCDB0EBBEB5FB8F96D2EBBE76FF9770683D558A079B90E0A8FDF72F21B549ED3C3A0721B14A6CBC3F3370B54B6A7E96550BC5E06BD41E4F27CFC76D3DFA079591D068DC3EE71991D26BF5DA06178FE06A9C3207AD98D0E83CAE632BD1E26BF416F103C7C0EB7CB6EFA1B640EDBDF7250D96D4F87E5A03768FC6EC3E56F7BD84D2F83E0',
  '617918247EB3CBF4F71C6E06B2D3E4B23CEC1E87C76FB13CEC1E87E7AEF1BBED12CB41F0B03C0C1287D3F830A8DC06CDD3737AB91D7601'
];

console.log(parts.map(Helper.decode7Bit).join(''));
```

Make shure you have a version 1.0.10

**Comment by jackkum** [comment]
```javascript
var PDU    = require('./pdu');
var Submit = PDU.Submit();

Submit.setAddress('+999999999999');
Submit.setData('sms_manu_pfofensor_3005, seu acordo esta em atraso, evite que o desconto seja cancelado. Caso ja tenha efetuado o pagamento favor enviar o comprovante para boletospf@liderancacobrancas.com.br para baixa em sistema');
Submit.getType().setSrr(1);

Submit.getParts()
  .forEach(function(part){
    console.log('' + part);

    var p = PDU.parse('' + part);
    console.log(p.getData().getData());
  });
```

I got this:
0061000C919999999999990000A006080432E40201F3F6FCDB0EBBEB5FB8F96D2EBBE76FF9770683D558A079B90E0A8FDF72F21B549ED3C3A0721B14A6CBC3F3370B54B6A7E96550BC5E06BD41E4F27CFC76D3DFA079591D068DC3EE71991D26BF5DA06178FE06A9C3207AD98D0E83CAE632BD1E26BF416F103C7C0EB7CB6EFA1B640EDBDF7250D96D4F87E5A03768FC6EC3E56F7BD84D2F83E0
sms_manu_pfofensor_3005, seu acordo esta em atraso, evite que o desconto seja cancelado. Caso ja tenha efetuado o pagamento favor enviar o comprovante p
0061000C9199999999999900004506080432E40202617918247EB3CBF4F71C6E06B2D3E4B23CEC1E87C76FB13CEC1E87E7AEF1BBED12CB41F0B03C0C1287D3F830A8DC06CDD3737AB91D06
ara boletospf@liderancacobrancas.com.br para baixa em sistema

**Comment by rubensfernandes** [comment]
:( still wrong on phone, i received sms§manu§pfofensor§3005 instead sms_manu_pfofensor_3005
try here -> https://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-pdu-decoder/

**Comment by rubensfernandes** [comment]
i think something wrong with 7bit encode function;

const sevenbitdefault = ['@', '£', '$', '¥', 'è', 'é', 'ù', 'ì', 'ò', 'Ç', '\n', 'Ø', 'ø', '\r', 'Å', 'å', '\u0394', '_', '\u03a6', '\u0393', '\u039b', '\u03a9', '\u03a0', '\u03a8', '\u03a3', '\u0398', '\u039e', '€', 'Æ', 'æ', 'ß', 'É', ' ', '!', '"', '#', '¤', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '¡', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'Ä', 'Ö', 'Ñ', 'Ü', '§', '¿', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'ä', 'ö', 'ñ', 'ü', 'à'];

function getSevenBit(character) //sp
{
    for (var i = 0; i < sevenbitdefault.length; i++)
    {
        if (sevenbitdefault[i] == character)
        {
            return i;
        }
    }

    console.log('No 7 bit char for ' + character);
    return 0;
}

**Comment by rubensfernandes** [comment]
instead of getting the charCode of letter i get the position from the sevenbit default chars
```
 for (let i = 0; i < str.length; i++) {
        console.log('7 bit default GSM table', getSevenBit(str.charAt(i)).toString(16).toUpperCase());
        console.log('NORMAL', str.charCodeAt(i).toString(16).toUpperCase());
 }
```

**Comment by jackkum** [comment]
Hi @rubensfernandes sorry for delay.
You are right, should be used a different ascii table. 
![ascii-gsm7](https://user-images.githubusercontent.com/2418167/26911668-964401da-4c41-11e7-8b5b-c6d2fc2d5ae6.png)
Here symbol '_' have a code 0x11 but here 
![ascii-table-wide svg](https://user-images.githubusercontent.com/2418167/26911820-a7c73f2a-4c42-11e7-89bd-ea2e53dab22b.png) he is equal 0x5F
